name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage coveralls pytest
          pip install -e .
      - name: Run python tests
        run: |
          pytest -rA
